# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  鲁强的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
rss_url: 

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: 
# weibo:    ID
github: frankqiang
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://static.pictureknow.com/03634afd690a42c5a178a6ec479f2cea.png 
favicon: http://static.pictureknow.com/03634afd690a42c5a178a6ec479f2cea.png 

# disqus 设置
disqus:
  shortname: yank-zh

# google analytics 设置
ga:
  id:
  url:

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
